openapi: 3.0.0
info:
  title: Kafka Connect REST API
  description: Kafka Connect REST API https://docs.confluent.io/platform/current/connect/references/restapi.html
  version: 0.1.9
paths:
  /:
    # https://docs.confluent.io/platform/current/connect/references/restapi.html#get--
    get:
      operationId: getClusterInfo
      summary: Top-level (root) request that gets the version of the Connect worker that serves the REST request, the git commit ID of the source code, and the Kafka cluster ID that the worker is connected to.
      responses:
        '200':
          $ref: '#/components/responses/GetClusterInfoResponse'
        '500':
          $ref: '#/components/responses/ServerErrorResponse'
        '503':
          $ref: '#/components/responses/ServiceUnavailableResponse'
  /connectors:
    # https://docs.confluent.io/platform/current/connect/references/restapi.html#get--connectors
    get:
      operationId: listConnectors
      summary: Get a list of active connectors.
      parameters:
        - $ref: '#/components/parameters/ExpandParameter'
      responses:
        '200':
          $ref: '#/components/responses/ListConnectorsResponse'
        '500':
          $ref: '#/components/responses/ServerErrorResponse'
        '503':
          $ref: '#/components/responses/ServiceUnavailableResponse'
    # https://docs.confluent.io/platform/current/connect/references/restapi.html#post--connectors
    post:
      operationId: createConnector
      summary: Create a new connector, returning the current connector info if successful. Return 409 (Conflict) if rebalance is in process, or if the connector already exists.
      requestBody:
        $ref: '#/components/requestBodies/CreateConnectorRequest'
      responses:
        '200':
          $ref: '#/components/responses/CreateConnectorResponse'
        '409':
          $ref: '#/components/responses/ConflictResponse'
        '422':
          $ref: '#/components/responses/UnprocessableEntityResponse'
        '500':
          $ref: '#/components/responses/ServerErrorResponse'
        '503':
          $ref: '#/components/responses/ServiceUnavailableResponse'

  /connectors/{name}:
    # https://docs.confluent.io/platform/current/connect/references/restapi.html#get--connectors-(string-name)
    get:
      operationId: getConnector
      summary: Get information about the connector.
      parameters:
        - $ref: '#/components/parameters/ConnectorNameParameter'
      responses:
        '200':
          $ref: '#/components/responses/GetConnectorResponse'
        '500':
          $ref: '#/components/responses/ServerErrorResponse'
        '503':
          $ref: '#/components/responses/ServiceUnavailableResponse'
    # https://docs.confluent.io/platform/current/connect/references/restapi.html#delete--connectors-(string-name)-
    delete:
      operationId: deleteConnector
      summary: Delete a connector, halting all tasks and deleting its configuration.
      parameters:
        - $ref: '#/components/parameters/ConnectorNameParameter'
      responses:
        '204':
          $ref: '#/components/responses/NoContentResponse'
        '409':
          $ref: '#/components/responses/ConflictResponse'
        '500':
          $ref: '#/components/responses/ServerErrorResponse'
        '503':
          $ref: '#/components/responses/ServiceUnavailableResponse'

  /connectors/{name}/status:
    # https://docs.confluent.io/platform/current/connect/references/restapi.html#get--connectors-(string-name)-status
    get:
      operationId: getConnectorStatus
      summary: |
        Gets the current status of the connector, including:
        * whether it is running or restarting, or if it has failed or paused
        * which worker it is assigned to
        * error information if it has failed
        * the state of all its tasks
      parameters:
        - $ref: '#/components/parameters/ConnectorNameParameter'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    description: Name of the connector.
                  connector:
                    type: object
                    description: Connector status.
                    properties:
                      state:
                        type: string
                        description: State of the connector.
                      worker_id:
                        type: string
                        description: ID of the worker running the connector.
                  tasks:
                    type: array
                    description: List of task status for the connector.
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                          description: ID of the task.
                        state:
                          type: string
                          description: Current state of the task.
                        worker_id:
                          type: string
                          description: ID of the worker running the task.
                        trace:
                          type: string
                          description: Stack trace information if the task has failed.
  /connectors/{name}/restart:
    # https://docs.confluent.io/platform/current/connect/references/restapi.html#post--connectors-(string-name)-restart
    post:
      operationId: restartConnector
      summary: Restart the connector. You may use the following query parameters to restart any combination of the Connector and/or Task instances for the connector.
      parameters:
        - $ref: '#/components/parameters/ConnectorNameParameter'
        - $ref: '#/components/parameters/IncludeTasksParameter'
        - $ref: '#/components/parameters/OnlyFailedParameter'
      responses:
        '200':
          $ref: '#/components/responses/OKResponse'
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                type: object
        '204':
          $ref: '#/components/responses/NotContentResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
        '409':
          $ref: '#/components/responses/ConflictResponse'
        '500':
          $ref: '#/components/responses/ServerErrorResponse'
        '503':
          $ref: '#/components/responses/ServiceUnavailableResponse'

  /connectors/{name}/pause:
    # https://docs.confluent.io/platform/current/connect/references/restapi.html#put--connectors-(string-name)-pause
    put:
      operationId: pauseConnector
      summary: Pause the connector and its tasks, which stops message processing until the connector is resumed. This call asynchronous and the tasks will not transition to PAUSED state at the same time.
      parameters:
        - $ref: '#/components/parameters/ConnectorNameParameter'
      responses:
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                type: object
        '409':
          $ref: '#/components/responses/ConflictResponse'
        '500':
          $ref: '#/components/responses/ServerErrorResponse'
        '503':
          $ref: '#/components/responses/ServiceUnavailableResponse'

  /connectors/{name}/resume:
    # https://docs.confluent.io/platform/current/connect/references/restapi.html#put--connectors-(string-name)-resume
    put:
      operationId: resumeConnector
      summary: Resume a paused connector or do nothing if the connector is not paused. This call asynchronous and the tasks will not transition to RUNNING state at the same time.
      parameters:
        - $ref: '#/components/parameters/ConnectorNameParameter'
      responses:
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                type: object
        '500':
          $ref: '#/components/responses/ServerErrorResponse'
        '503':
          $ref: '#/components/responses/ServiceUnavailableResponse'
components:
  parameters:
    ConnectorNameParameter:
      name: name
      description: Name of the connector.
      in: path
      required: true
      schema:
        type: string
    ExpandParameter:
      name: expand
      description: Retrieves additional state/configuration information for each of the connectors returned in the API call.
      in: query
      required: false
      schema:
        type: array
        items:
          type: string
          enum: ["info", "status"]
    IncludeTasksParameter:
      name: includeTasks
      description: Specifies whether to restart the connector instance and task instances (includeTasks=true) or just the connector instance (includeTasks=false).
      in: query
      required: false
      schema:
        type: boolean
    OnlyFailedParameter:
      name: onlyFailed
      description: Specifies whether to restart just the instances with a FAILED status (onlyFailed=true) or all instances (onlyFailed=false).
      in: query
      schema:
        type: boolean
      required: false
  requestBodies:
    CreateConnectorRequest:
      description: New connector request.
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateConnectorRequest'
  responses:
    GetClusterInfoResponse:
      description: Cluster info retrieved successfully.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GetClusterInfoResponse'
    CreateConnectorResponse:
      description: New connector created successfully.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateConnectorResponse'
    GetConnectorResponse:
      description: Connector fetched successfully.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GetConnectorResponse'
    ListConnectorsResponse:
      description: Connectors fetched successfully.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ListConnectorsResponse'
    OKResponse:
      description: OK.
    CreatedResponse:
      description: Created
    NoContentResponse:
      description: No Content
    ForbiddenResponse:
      description: Forbidden
    ConflictResponse:
      description: Conflict. Rebalance in progress.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
        text/plain:
          schema:
            type: string
    NotFoundResponse:
      description: Resource not found.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
        text/plain:
          schema:
            type: string
    UnprocessableEntityResponse:
      description: Unprocessable Entity.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
        text/plain:
          schema:
            type: string
    ServerErrorResponse:
      description: Internal Server Error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
        text/plain:
          schema:
            type: string
    ServiceUnavailableResponse:
      description: Service Unavailable.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
        text/plain:
          schema:
            type: string
    UnexpectedErrorResponse:
      description: Unexpected Error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
        text/plain:
          schema:
            type: string
  schemas:
    Error:
      type: object
      description: Generic error.
      properties:
        error_code:
          type: number
          description: Error code.
        message:
          type: string
          description: Error message.
    GetClusterInfoResponse:
      type: object
      properties:
        version:
          type: string
          description: Connect worker version.
        commit:
          type: string
          description: git commit ID.
        kafka_cluster_id:
          type: string
          description: Kafka cluster ID.
    CreateConnectorRequest:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/ConnectorName'
        config:
          $ref: '#/components/schemas/Config'
    CreateConnectorResponse:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/ConnectorName'
        config:
          $ref: '#/components/schemas/Config'
        tasks:
          type: array
          description: Lits of active tasks generated by the connector.
          items:
            type: object
            properties:
              connector:
                $ref: '#/components/schemas/ConnectorName'
              task:
                $ref: '#/components/schemas/TaskID'
    ListConnectorsResponse:
      type: object
      description: List of connectors.
      additionalProperties: true
    GetConnectorResponse:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/ConnectorName'
        config:
          $ref: '#/components/schemas/Config'
        tasks:
          type: array
          description: List of active tasks generated by the connector.
          items:
            type: object
            properties:
              connector:
                $ref: '#/components/schemas/ConnectorName'
              task:
                $ref: '#/components/schemas/TaskID'
    GetConnectorStatusResponse:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/ConnectorName'
        connector:
          type: object
          description: Connector status.
          properties:
            state:
              $ref: '#/components/schemas/State'
            worker_id:
              $ref: '#/components/schemas/WorkerID'
        tasks:
          type: array
          description: List of task status for the connector.
          items:
            type: object
            properties:
              id:
                $ref: '#/components/schemas/TaskID'
              trace:
                $ref: '#/components/schemas/TaskTrace'
              state:
                $ref: '#/components/schemas/State'
              worker_id:
                $ref: '#/components/schemas/WorkerID'
    Config:
      type: object
      description: Configuration of a connector/task/worker. All keys/values should be strings.
    ConnectorName:
      type: string
      description: Name of the connector.
    TaskID:
      type: number
      description: ID of the task.
    TaskTrace:
      type: string
      description: Stack trace information if the task has failed.
    State:
      type: string
      description: State of a connector/task/worker.
      enum: ["UNASSIGNED", "RUNNING", "PAUSED", "FAILED", "RESTARTING", "DESTROYED"]
    WorkerID:
      type: string
      description: ID of the worker.
