openapi: 3.0.0
info:
  title: Kafka Connect REST API
  description: Kafka Connect REST API https://docs.confluent.io/platform/current/connect/references/restapi.html
  version: 0.1.9
paths:
  /:
    # https://docs.confluent.io/platform/current/connect/references/restapi.html#get--
    get:
      operationId: getClusterInfo
      summary: Top-level (root) request that gets the version of the Connect worker that serves the REST request, the git commit ID of the source code, and the Kafka cluster ID that the worker is connected to.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    type: string
                    description: Connect worker version.
                  commit:
                    type: string
                    description: git commit ID.
                  kafka_cluster_id:
                    type: string
                    description: Kafka cluster ID.

  /connectors:
    # https://docs.confluent.io/platform/current/connect/references/restapi.html#get--connectors
    get:
      operationId: listConnectors
      summary: Get a list of active connectors.
      parameters:
        - name: expand
          in: query
          schema:
            type: array
            items:
              type: string
          required: false
          description: Retrieves additional state/configuration information for each of the connectors returned in the API call.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                description: List of connectors.
                additionalProperties: true
    # https://docs.confluent.io/platform/current/connect/references/restapi.html#post--connectors
    post:
      operationId: createConnector
      summary: Create a new connector, returning the current connector info if successful. Return 409 (Conflict) if rebalance is in process, or if the connector already exists.
      requestBody:
        description: New connector request body
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Name of the connector to create
                config:
                  type: object
                  description: Configuration parameters for the connector. All values should be strings.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    description: Name of the created connector
                  config:
                    type: object
                    description: Configuration parameters for the connector.
                  tasks:
                    type: array
                    description: Lits of active tasks generated by the connector.
                    items:
                      type: object
                      properties:
                        connector:
                          type: string
                          description: The name of the connector the task belongs to.
                        task:
                          type: number
                          description: Task ID within the connector.

  /connectors/{name}:
    # https://docs.confluent.io/platform/current/connect/references/restapi.html#get--connectors-(string-name)
    get:
      operationId: getConnector
      summary: Get information about the connector.
      parameters:
        - name: name
          in: path
          schema:
            type: string
          required: true
          description: Name of the created connector.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    description: Name of the created connector.
                  config:
                    type: object
                    description: Configuration parameters for the connector.
                  tasks:
                    type: array
                    description: List of active tasks generated by the connector.
                    items:
                      type: object
                      properties:
                        connector:
                          type: string
                          description: The name of the connector the task belongs to.
                        task:
                          type: number
                          description: Task ID within the connector.
    # https://docs.confluent.io/platform/current/connect/references/restapi.html#delete--connectors-(string-name)-
    delete:
      operationId: deleteConnector
      summary: Delete a connector, halting all tasks and deleting its configuration.
      parameters:
        - name: name
          in: path
          schema:
            type: string
          required: true
          description: Name of the created connector.
      responses:
        '204':
          description: No Content
        '409':
          description: Rebalance in progress

  /connectors/{name}/status:
    # https://docs.confluent.io/platform/current/connect/references/restapi.html#get--connectors-(string-name)-status
    get:
      operationId: getConnectorStatus
      summary: |
        Gets the current status of the connector, including:
        * whether it is running or restarting, or if it has failed or paused
        * which worker it is assigned to
        * error information if it has failed
        * the state of all its tasks
      parameters:
        - name: name
          in: path
          schema:
            type: string
          required: true
          description: Name of the created connector.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    description: Name of the connector.
                  connector:
                    type: object
                    description: Connector status.
                    properties:
                      state:
                        type: string
                        description: State of the connector.
                      worker_id:
                        type: string
                        description: ID of the worker running the connector.
                  tasks:
                    type: array
                    description: List of task status for the connector.
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                          description: ID of the task.
                        state:
                          type: string
                          description: Current state of the task.
                        worker_id:
                          type: string
                          description: ID of the worker running the task.
                        trace:
                          type: string
                          description: Stack trace information if the task has failed.
  /connectors/{name}/restart:
    # https://docs.confluent.io/platform/current/connect/references/restapi.html#post--connectors-(string-name)-restart
    post:
      operationId: restartConnector
      summary: Restart the connector. You may use the following query parameters to restart any combination of the Connector and/or Task instances for the connector.
      parameters:
        - name: name
          in: path
          schema:
            type: string
          required: true
          description: Name of the connector.
        - name: includeTasks
          in: query
          schema:
            type: boolean
          required: false
          description: Specifies whether to restart the connector instance and task instances (includeTasks=true) or just the connector instance (includeTasks=false).
        - name: onlyFailed
          in: query
          schema:
            type: boolean
          required: false
          description: Specifies whether to restart just the instances with a FAILED status (onlyFailed=true) or all instances (onlyFailed=false).
      responses:
        '200':
          description: OK
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                type: object
        '204':
          description: No Content
        '404':
          description: Not Found
        '409':
          description: Rebalance in progress
        '500':
          description: Internal Server Error

  /connectors/{name}/pause:
    # https://docs.confluent.io/platform/current/connect/references/restapi.html#put--connectors-(string-name)-pause
    put:
      operationId: pauseConnector
      summary: Pause the connector and its tasks, which stops message processing until the connector is resumed. This call asynchronous and the tasks will not transition to PAUSED state at the same time.
      parameters:
        - name: name
          in: path
          schema:
            type: string
          required: true
          description: Name of the connector to pause.
      responses:
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Internal Server Error

  /connectors/{name}/resume:
    # https://docs.confluent.io/platform/current/connect/references/restapi.html#put--connectors-(string-name)-resume
    put:
      operationId: resumeConnector
      summary: Resume a paused connector or do nothing if the connector is not paused. This call asynchronous and the tasks will not transition to RUNNING state at the same time.
      parameters:
        - name: name
          in: path
          schema:
            type: string
          required: true
          description: Name of the connector to resume.
      responses:
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Internal Server Error
